import React, { useState, ReactElement } from 'react';

interface Props {
    // onSearchPosts: StringCallback;
}

export default function HomePage({ ...rest }: Props): ReactElement<Props> {
    return (
        <div>
        <section>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec dui laoreet, suscipit est placerat, dapibus ipsum. Integer scelerisque nunc eget orci tristique, at posuere nibh consectetur. Maecenas eget odio tristique, efficitur magna vitae, vulputate orci. Pellentesque commodo eget urna placerat sollicitudin. Etiam volutpat dignissim turpis, in hendrerit nulla consectetur bibendum. Aliquam sit amet quam sed tellus hendrerit scelerisque eu eget quam. Nam quis augue dolor. In accumsan augue quam, vitae posuere sapien egestas elementum. Aliquam porttitor tortor non mi eleifend, nec suscipit lorem tincidunt. Nam sit amet quam tortor. Proin sollicitudin aliquam malesuada. Nullam pulvinar mattis viverra. Cras at nisl vulputate, malesuada metus ac, ornare mauris. Integer in metus a leo volutpat rhoncus. Vivamus rhoncus tristique nibh. Duis in mi rhoncus neque mattis molestie at quis felis.
        </section>

        <section>
            Cras sit amet sagittis ipsum, id porttitor nunc. In ut diam ut neque scelerisque malesuada. Phasellus in odio eu nunc consectetur viverra. Ut laoreet est mi, ut mattis ex bibendum non. Fusce feugiat convallis lorem, at vestibulum turpis ultricies egestas. Phasellus eu nisi lectus. Donec lacinia cursus enim, eget condimentum metus viverra at. Phasellus sagittis velit non lacinia placerat. Phasellus sagittis hendrerit sapien, a egestas dolor ultrices eget. Nulla facilisi. Maecenas facilisis, nisl eget sollicitudin varius, dolor tortor luctus sapien, eu aliquam felis mi at ante. Quisque dignissim lectus sit amet laoreet pretium. Etiam non turpis condimentum nulla bibendum iaculis quis sit amet odio. Proin purus augue, venenatis nec finibus a, congue eu tellus. Sed blandit, leo a iaculis lacinia, dolor odio feugiat justo, et porta erat turpis a dui.
        </section>
        <section>
            Donec volutpat tempor turpis, et sollicitudin diam scelerisque in. Fusce ultricies varius risus vel malesuada. Praesent pellentesque at odio a eleifend. Nunc scelerisque ex leo, ac vulputate massa mollis sit amet. Integer et odio pharetra, maximus dolor eu, scelerisque nulla. Nunc in mattis sem. Quisque malesuada sed neque quis aliquam. Pellentesque malesuada dapibus nisi, vitae porttitor sem convallis a. Donec sollicitudin, nulla id porta tempor, ante lectus rutrum dolor, nec sollicitudin augue nibh vel quam. Mauris ac urna nisi. Ut eu tempus nunc. Phasellus eget lorem diam. Aenean quis imperdiet erat. Quisque ac cursus ipsum, eu ornare lectus. Morbi rutrum nisi ante, non posuere metus auctor nec. Sed ut massa ut felis ornare auctor.
        </section>
        <section>
            Cras vitae urna leo. Proin nisi mauris, bibendum id tincidunt in, consectetur nec ligula. Donec eget elit nec tortor egestas euismod. Vestibulum tempor lorem a quam sodales placerat. Praesent sagittis sem ut urna ullamcorper vestibulum. Vestibulum sed vulputate purus, eu lobortis dolor. Cras eu massa ut mi bibendum hendrerit. Suspendisse semper orci sit amet est molestie, eu pellentesque diam condimentum. Praesent in nulla tristique, semper dolor vitae, condimentum orci. Praesent ullamcorper eros sagittis, volutpat sapien quis, posuere sem. Pellentesque est mi, maximus nec leo at, pulvinar tincidunt elit. Sed molestie lectus quis vestibulum ornare. Fusce nec diam sit amet lacus facilisis rutrum ut et purus. Fusce nibh quam, interdum et arcu in, tempor consequat justo.
        </section>
        <section>
            Fusce faucibus elementum ex, in lobortis erat lobortis sed. Phasellus nec luctus lacus. Sed eget volutpat velit. Nulla ex leo, fermentum eu neque vitae, facilisis blandit magna. Vivamus vulputate cursus imperdiet. Nullam ullamcorper felis et ipsum elementum molestie. Duis rhoncus ultricies nulla, sed posuere quam tempus in. Maecenas egestas vel nunc et convallis. Sed et lectus sem. Suspendisse potenti. Nam nec commodo ipsum.
        </section>
            <section>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec dui laoreet, suscipit est placerat, dapibus ipsum. Integer scelerisque nunc eget orci tristique, at posuere nibh consectetur. Maecenas eget odio tristique, efficitur magna vitae, vulputate orci. Pellentesque commodo eget urna placerat sollicitudin. Etiam volutpat dignissim turpis, in hendrerit nulla consectetur bibendum. Aliquam sit amet quam sed tellus hendrerit scelerisque eu eget quam. Nam quis augue dolor. In accumsan augue quam, vitae posuere sapien egestas elementum. Aliquam porttitor tortor non mi eleifend, nec suscipit lorem tincidunt. Nam sit amet quam tortor. Proin sollicitudin aliquam malesuada. Nullam pulvinar mattis viverra. Cras at nisl vulputate, malesuada metus ac, ornare mauris. Integer in metus a leo volutpat rhoncus. Vivamus rhoncus tristique nibh. Duis in mi rhoncus neque mattis molestie at quis felis.
            </section>

            <section>
                Cras sit amet sagittis ipsum, id porttitor nunc. In ut diam ut neque scelerisque malesuada. Phasellus in odio eu nunc consectetur viverra. Ut laoreet est mi, ut mattis ex bibendum non. Fusce feugiat convallis lorem, at vestibulum turpis ultricies egestas. Phasellus eu nisi lectus. Donec lacinia cursus enim, eget condimentum metus viverra at. Phasellus sagittis velit non lacinia placerat. Phasellus sagittis hendrerit sapien, a egestas dolor ultrices eget. Nulla facilisi. Maecenas facilisis, nisl eget sollicitudin varius, dolor tortor luctus sapien, eu aliquam felis mi at ante. Quisque dignissim lectus sit amet laoreet pretium. Etiam non turpis condimentum nulla bibendum iaculis quis sit amet odio. Proin purus augue, venenatis nec finibus a, congue eu tellus. Sed blandit, leo a iaculis lacinia, dolor odio feugiat justo, et porta erat turpis a dui.
            </section>
            <section>
                Donec volutpat tempor turpis, et sollicitudin diam scelerisque in. Fusce ultricies varius risus vel malesuada. Praesent pellentesque at odio a eleifend. Nunc scelerisque ex leo, ac vulputate massa mollis sit amet. Integer et odio pharetra, maximus dolor eu, scelerisque nulla. Nunc in mattis sem. Quisque malesuada sed neque quis aliquam. Pellentesque malesuada dapibus nisi, vitae porttitor sem convallis a. Donec sollicitudin, nulla id porta tempor, ante lectus rutrum dolor, nec sollicitudin augue nibh vel quam. Mauris ac urna nisi. Ut eu tempus nunc. Phasellus eget lorem diam. Aenean quis imperdiet erat. Quisque ac cursus ipsum, eu ornare lectus. Morbi rutrum nisi ante, non posuere metus auctor nec. Sed ut massa ut felis ornare auctor.
            </section>
            <section>
                Cras vitae urna leo. Proin nisi mauris, bibendum id tincidunt in, consectetur nec ligula. Donec eget elit nec tortor egestas euismod. Vestibulum tempor lorem a quam sodales placerat. Praesent sagittis sem ut urna ullamcorper vestibulum. Vestibulum sed vulputate purus, eu lobortis dolor. Cras eu massa ut mi bibendum hendrerit. Suspendisse semper orci sit amet est molestie, eu pellentesque diam condimentum. Praesent in nulla tristique, semper dolor vitae, condimentum orci. Praesent ullamcorper eros sagittis, volutpat sapien quis, posuere sem. Pellentesque est mi, maximus nec leo at, pulvinar tincidunt elit. Sed molestie lectus quis vestibulum ornare. Fusce nec diam sit amet lacus facilisis rutrum ut et purus. Fusce nibh quam, interdum et arcu in, tempor consequat justo.
            </section>
            <section>
                Fusce faucibus elementum ex, in lobortis erat lobortis sed. Phasellus nec luctus lacus. Sed eget volutpat velit. Nulla ex leo, fermentum eu neque vitae, facilisis blandit magna. Vivamus vulputate cursus imperdiet. Nullam ullamcorper felis et ipsum elementum molestie. Duis rhoncus ultricies nulla, sed posuere quam tempus in. Maecenas egestas vel nunc et convallis. Sed et lectus sem. Suspendisse potenti. Nam nec commodo ipsum.
            </section>
            <section>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec dui laoreet, suscipit est placerat, dapibus ipsum. Integer scelerisque nunc eget orci tristique, at posuere nibh consectetur. Maecenas eget odio tristique, efficitur magna vitae, vulputate orci. Pellentesque commodo eget urna placerat sollicitudin. Etiam volutpat dignissim turpis, in hendrerit nulla consectetur bibendum. Aliquam sit amet quam sed tellus hendrerit scelerisque eu eget quam. Nam quis augue dolor. In accumsan augue quam, vitae posuere sapien egestas elementum. Aliquam porttitor tortor non mi eleifend, nec suscipit lorem tincidunt. Nam sit amet quam tortor. Proin sollicitudin aliquam malesuada. Nullam pulvinar mattis viverra. Cras at nisl vulputate, malesuada metus ac, ornare mauris. Integer in metus a leo volutpat rhoncus. Vivamus rhoncus tristique nibh. Duis in mi rhoncus neque mattis molestie at quis felis.
            </section>

            <section>
                Cras sit amet sagittis ipsum, id porttitor nunc. In ut diam ut neque scelerisque malesuada. Phasellus in odio eu nunc consectetur viverra. Ut laoreet est mi, ut mattis ex bibendum non. Fusce feugiat convallis lorem, at vestibulum turpis ultricies egestas. Phasellus eu nisi lectus. Donec lacinia cursus enim, eget condimentum metus viverra at. Phasellus sagittis velit non lacinia placerat. Phasellus sagittis hendrerit sapien, a egestas dolor ultrices eget. Nulla facilisi. Maecenas facilisis, nisl eget sollicitudin varius, dolor tortor luctus sapien, eu aliquam felis mi at ante. Quisque dignissim lectus sit amet laoreet pretium. Etiam non turpis condimentum nulla bibendum iaculis quis sit amet odio. Proin purus augue, venenatis nec finibus a, congue eu tellus. Sed blandit, leo a iaculis lacinia, dolor odio feugiat justo, et porta erat turpis a dui.
            </section>
            <section>
                Donec volutpat tempor turpis, et sollicitudin diam scelerisque in. Fusce ultricies varius risus vel malesuada. Praesent pellentesque at odio a eleifend. Nunc scelerisque ex leo, ac vulputate massa mollis sit amet. Integer et odio pharetra, maximus dolor eu, scelerisque nulla. Nunc in mattis sem. Quisque malesuada sed neque quis aliquam. Pellentesque malesuada dapibus nisi, vitae porttitor sem convallis a. Donec sollicitudin, nulla id porta tempor, ante lectus rutrum dolor, nec sollicitudin augue nibh vel quam. Mauris ac urna nisi. Ut eu tempus nunc. Phasellus eget lorem diam. Aenean quis imperdiet erat. Quisque ac cursus ipsum, eu ornare lectus. Morbi rutrum nisi ante, non posuere metus auctor nec. Sed ut massa ut felis ornare auctor.
            </section>
            <section>
                Cras vitae urna leo. Proin nisi mauris, bibendum id tincidunt in, consectetur nec ligula. Donec eget elit nec tortor egestas euismod. Vestibulum tempor lorem a quam sodales placerat. Praesent sagittis sem ut urna ullamcorper vestibulum. Vestibulum sed vulputate purus, eu lobortis dolor. Cras eu massa ut mi bibendum hendrerit. Suspendisse semper orci sit amet est molestie, eu pellentesque diam condimentum. Praesent in nulla tristique, semper dolor vitae, condimentum orci. Praesent ullamcorper eros sagittis, volutpat sapien quis, posuere sem. Pellentesque est mi, maximus nec leo at, pulvinar tincidunt elit. Sed molestie lectus quis vestibulum ornare. Fusce nec diam sit amet lacus facilisis rutrum ut et purus. Fusce nibh quam, interdum et arcu in, tempor consequat justo.
            </section>
            <section>
                Fusce faucibus elementum ex, in lobortis erat lobortis sed. Phasellus nec luctus lacus. Sed eget volutpat velit. Nulla ex leo, fermentum eu neque vitae, facilisis blandit magna. Vivamus vulputate cursus imperdiet. Nullam ullamcorper felis et ipsum elementum molestie. Duis rhoncus ultricies nulla, sed posuere quam tempus in. Maecenas egestas vel nunc et convallis. Sed et lectus sem. Suspendisse potenti. Nam nec commodo ipsum.
            </section>
        </div>
    );
}